repos:
  - repo: https://github.com/pre-commit/mirrors-autopep8
    rev: v1.5.7
    hooks:
      - id: autopep8
        files: \.py$

  - repo: https://github.com/pre-commit/mirrors-flake8
    rev: v3.8.4
    hooks:
      - id: flake8
        files: \.py$

  - repo: https://github.com/pre-commit/mirrors-eslint
    rev: v7.32.0
    hooks:
      - id: eslint
        files: \.(js|jsx|ts|tsx)$

  - repo: https://github.com/pre-commit/mirrors-prettier
    rev: v2.5.1
    hooks:
      - id: prettier
        files: \.(js|jsx|ts|tsx|css|json|md)$
