version: '3.8'

services:
  postgres:
    image: postgres:latest
    container_name: my-postgres-db
    environment:
      POSTGRES_USER: ibenmain
      POSTGRES_PASSWORD: ibenmain123@
      POSTGRES_DB: e-learning-db
    ports:
      - "5433:5432"
    networks:
      - my-network
    volumes:
      - postgres_data:/var/lib/postgresql/data

  backend:
    build:
      context: ./e-learning-backend
    container_name: django-app
    command: /app/wait-for-db.sh python manage.py runserver 0.0.0.0:8000
    environment:
      DB_NAME: e-learning-db
      DB_USER: ibenmain
      DB_PASSWORD: ibenmain123@
      DB_HOST: postgres
      DB_PORT: '5432'
    ports:
      - "8000:8000"
    networks:
      - my-network
    depends_on:
      - postgres
    volumes:
      - ./e-learning-backend:/app

  frontend:
    build:
      context: ./e-learning-frontend
    container_name: react-app
    ports:
      - "3000:3000"
    networks:
      - my-network
    depends_on:
      - backend

volumes:
  postgres_data:

networks:
  my-network:
